version: 2.1

anchors:
  docker:
    gradle_docker: &sbt_docker
      docker:
        - image: circleci/openjdk:8u181-jdk
  workspace:
    save_workspace: &save_workspace
      persist_to_workspace:
        root: ./workspace
        paths:
          - '*'
    load_workspace: &load_workspace
      attach_workspace:
        at: '/tmp/workspace'

jobs:
  build_and_test:
    <<: *sbt_docker
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - sbt-repo-v2-{{ .Branch }}-{{ checksum "build.sbt" }}
            - sbt-repo-v2-{{ .Branch }}-
            - sbt-repo-v2-
      - run: sbt assembly
      - save_cache:
          paths:
            - ~/.ivy2/cache
            - ~/.m2
            - ~/.cache/coursier/v1
          key: sbt-repo-v2-{{ .Branch }}-{{ checksum "build.sbt" }}
      - run: mkdir -p workspace/builds && cp target/build/**.jar workspace/builds
      - *save_workspace
  deploy_debug:
    <<: *sbt_docker
    working_directory: ~/repo
    steps:
      - *load_workspace
      - run: scp -oStrictHostKeyChecking=no -P $HOST_PORT /tmp/workspace/builds/**.jar $DEBUG_DEPLOY_TARGET_HOST > /dev/null 2>&1
  deploy_production:
    <<: *sbt_docker
    working_directory: ~/repo
    steps:
      - *load_workspace
      - run: scp -oStrictHostKeyChecking=no -P $HOST_PORT /tmp/workspace/builds/**.jar $PRODUCTION_DEPLOY_TARGET_HOST > /dev/null 2>&1

workflows:
  version: 2
  test_and_build:
    jobs:
      - build_and_test
      - deploy_production:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master
      - deploy_debug:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - develop
